app:
  image:
    repository: "ghcr.io/s-baier/demo-app"
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  appPort: 9090
  ingress:
    enabled: true
    className: contour
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  hosts:
    - host: app.demo.cn.evoila-lab.work
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: app-tls
     hosts:
       - app.demo.cn.evoila-lab.work
